---
kind: pipeline
name: build

steps:
- name: build
  image: plugins/docker
  settings:
    dry_run: true
    repo: livingdocs/backport
    tags: [latest]

- name: release
  image: livingdocs/semantic-release:v1.0.0
  environment:
    GH_TOKEN:
      from_secret: GITHUB_TOKEN

trigger:
  event: [push]

---
kind: pipeline
name: tag

steps:
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: livingdocs/backport
    tags: ["${DRONE_TAG}", latest]

trigger:
  event: [tag]
---
kind: signature
hmac: 8a911994d468677c97613d10b33018236ff2ffba574cb5e5c7d8a49bd51cc743

...
